//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlyerFormat()
        {
            this.FlyerEventBases = new HashSet<FlyerEventBas>();
        }
    
        public int Id { get; set; }
        public string formatlong { get; set; }
        public string formatshort { get; set; }
        public bool isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerEventBas> FlyerEventBases { get; set; }
    }
}
