//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SupplierPricings = new HashSet<SupplierPricing>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int cost { get; set; }
        public int gross { get; set; }
        public int retail { get; set; }
        public bool isdeleted { get; set; }
        public int FlyerEventBase_Id { get; set; }
    
        public virtual FlyerEventBas FlyerEventBas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierPricing> SupplierPricings { get; set; }
    }
}
