//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public int Id { get; set; }
        public string shortname { get; set; }
        public string longname { get; set; }
        public int Region_Id { get; set; }
    
        public virtual Region Region { get; set; }
    }
}
