//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlyerOrder()
        {
            this.Distributors = new HashSet<Distributor>();
        }
    
        public int Id { get; set; }
        public string amoutordered { get; set; }
        public System.DateTime dateordered { get; set; }
        public string orderedby { get; set; }
        public bool isdeleted { get; set; }
        public string lastchanged { get; set; }
        public int FlyerEventBase_Id { get; set; }
        public int DealerBase_Id { get; set; }
    
        public virtual DealerBas DealerBas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Distributor> Distributors { get; set; }
        public virtual FlyerEventBas FlyerEventBas { get; set; }
    }
}
