//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerEventBas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlyerEventBas()
        {
            this.FlyerOrders = new HashSet<FlyerOrder>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public string theme { get; set; }
        public bool isdeleted { get; set; }
        public int Theme_Id { get; set; }
        public int FlyerFormat_Id { get; set; }
        public int FlyerType_Id { get; set; }
        public int FlyerSchedule_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerOrder> FlyerOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual FlyerType FlyerType { get; set; }
        public virtual FlyerFormat FlyerFormat { get; set; }
        public virtual FlyerSchedule FlyerSchedule { get; set; }
        public virtual Theme Theme1 { get; set; }
    }
}
