//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoursOfOperation
    {
        public int Id { get; set; }
        public string day { get; set; }
        public string opentime { get; set; }
        public string closetime { get; set; }
        public bool isdeleted { get; set; }
        public bool isclosed { get; set; }
        public int DealerBase_Id { get; set; }
    
        public virtual DealerBas DealerBas { get; set; }
    }
}
