//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierPricing
    {
        public int Id { get; set; }
        public int cost { get; set; }
        public int SupplierBase_Id { get; set; }
        public int Product_Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SupplierBas SupplierBas { get; set; }
    }
}
