//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerEventBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlyerEventBase()
        {
            this.Products = new HashSet<Product>();
            this.FlyerTypes = new HashSet<FlyerType>();
            this.FlyerOrders = new HashSet<FlyerOrder>();
        }
    
        public int Id { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime end { get; set; }
        public string theme { get; set; }
        public bool isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Theme Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerType> FlyerTypes { get; set; }
        public virtual FlyerFormat FlyerFormat { get; set; }
        public virtual FlyerSchedule FlyerSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerOrder> FlyerOrders { get; set; }
    }
}
