//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlyerSchedule()
        {
            this.FlyerEventBases = new HashSet<FlyerEventBase>();
        }
    
        public int Id { get; set; }
        public System.DateTimeOffset tminus { get; set; }
        public int order { get; set; }
        public string scheduleevent { get; set; }
        public bool iscomplete { get; set; }
        public bool isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlyerEventBase> FlyerEventBases { get; set; }
    }
}
