//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyerCreationApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerOrder
    {
        public int Id { get; set; }
        public string amoutordered { get; set; }
        public System.DateTime dateordered { get; set; }
        public string orderedby { get; set; }
        public bool isdeleted { get; set; }
        public string lastchanged { get; set; }
    
        public virtual FlyerEventBase FlyerEventBase { get; set; }
        public virtual DealerBase DealerBase { get; set; }
    }
}
